### ISSUE TITLE
Haxe 3.2.0 compatibility

### ISSUE THREAD

**Issue by azrafe7** [fponticelli/sui#13]
I'd love to play with this nice lib, but it seems to not be compatible with haxe 3.2.0 (yet?).

Most of the errors I'm getting are related to the latest changes/renamings in the js.html packages/modules (Element vs DOMElement). Have tried to fix it myself, but the errors also covered the dependent libs (dots, stream, etc.).

Any hints on how could I patch it myself, or if you're planning to bring the lib up-to-date with 3.2.0?

**Comment by fponticelli** [comment]
I am aware of the changes and yes, there are at least 2 libraries involved. I will try to do my best to bring them up to speed. If you have the time and want to give it a try I will gladly accept a PR.

No particular hint except follow the errors :)

**Comment by azrafe7** [comment]
I've followed the errors as you suggested, and all seems fine as of now (i.e. all demos compiling).
(it was easier than expected... I'm very impressed by your coding style! :smile:)

Not sure I fixed all occurences of `js.html.Element`, but it's a good start. I've aliased `DOMElement` to `Element` in case there'd be some changes to the API (which is probable as of https://github.com/HaxeFoundation/haxe/issues/4081).

Involved libs were `sui`, `dots` and `stream.dom`. Sending a PR very soon in case you're willing to bring it in.

**Comment by fponticelli** [comment]
Thank you very much, appreciated!

Il giorno gio 16 apr 2015 alle ore 15:44 Giuseppe Di Mauro <
notifications@github.com> ha scritto:

**Comment by fponticelli** [comment]
I think we can close this now, right? Thank you very much!

**Comment by azrafe7** [comment]
Yes, and you're very welcome!

2015-04-17 0:48 GMT+02:00 Franco Ponticelli <notifications@github.com>:

**Comment by fponticelli** [comment]
Let me know how SUI works for you ;)

**Comment by azrafe7** [comment]
Hey @fponticelli, I really like your lib and its minimalist style! Here's some additional feedback.

 - support for enums would be a nice addition (I see you've already planned for that)
 - couldn't find a way to change the label of a control at runtime (but maybe is already possible?)
 - how to validate/enforce the bounds of a range control when editing its value (i.e. when actually typing it)?
 - add possibility to specify a label when using `bind`
 - add a customizable delay to wait before firing the _onChange_ callback
 - `text()` in listonly mode doesn't fill all the horizontal space
 - multi range controls would make me very happy too ;D
 - support for radio boxes

**Comment by fponticelli** [comment]
* yes, enum support is planned but it is tricky. It requires a "ChoiceControl" to be able to switch from one set of controls to another but that proved to be tricky. Here is the starting point: https://github.com/fponticelli/sui/blob/master/src/sui/controls/ChoiceControl.hx
  * retrieving the label of a control generated with `Sui.create*` or `Sui.control` is not easy (and probably not even possible). To do that you have to create your controls and containers directly. What would be a real world example where that is useful? If you need to output something you can create a readonly text-control. In any case an easy solution would be to add a parallel function to `Sui.control` that takes a control for a label ... in that case you control it with as much details as you want.
  * setting the label when using bind is not possible at the moment but should not be too bad to add. We can add an optional parameter to `bind` for that.
  * about the delay, wouldn't it better to add a debounce on your setter function if that is required?
  * about `text()` in listonly mode it is probably a CSS issue, should be easy to fix (I hope)
  * how would a multi-range control work?
  * what is the difference between radio boxes and a drop list in this context? We could add a flag that under a certain number of options (3 or 4), radios are used ... it might still have some strange visual effect when it overflows the available space.

Feel free to open individual issues for each of these topics .... I am not sure I can give you them all but I can try :) ... also PR are always welcome.

**Comment by azrafe7** [comment]
**enums**: I'll probably wait for you to implement this, and resort to text lists in the meantime ;)
**change control label**: I'll see if I can come up with something by following your suggestions (for a real case: I have a "vertex count" slider that should be changed to "circle count" depending on the state of a droplist control, while retaining the same min/max/step)
**label with bind**: that seems not too difficult to add
**delay**: can you expand on what you mean by "add a debounce on your setter"?
**text listonly**: yep it seems a CSS issue, I've added `... select` to the things that have `width:100%` and it seems to work (not sure it's a complete fix though)
**multirange slider**: something like the gradient composer in photo editing apps or these http://www.jqueryscript.net/tags.php?/Range%20Slider/
**radio boxes**: no difference, apart from the fact that all possible values are visible without needing to open the droplist, so your idea of merging them and expose a flag might be a very good one!

Oh, and you missed a question about enforcing/validating values, but that's could closely related to the delay one!?

Waiting for you to comment on these, and then I'll probably file separate issues.

**Comment by azrafe7** [comment]
I've solved my label problem by creating a `LabelControl` explicitly (as suggested) and using `grid.add()` afterwards (which needed subclassing or `@:access()`).
The enum has been solved by using text lists in tandem with `Type.createEnum()` (not so elegant - I know -, but works).
What I miss is the delay/debounce functionality, can you elaborate on that?

(my use case is [here](https://github.com/azrafe7/hxClipper/blob/7f04cad524414f315f8d2b94796d68fbfd261f7c/src/SuiDemoJS.hx#L106-L111), in case you're curious)

**Comment by fponticelli** [comment]
Every time you bind a control to a value you are actually setting up a setter function. Much like you do here: https://github.com/azrafe7/hxClipper/blob/7f04cad524414f315f8d2b94796d68fbfd261f7c/src/SuiDemoJS.hx#L116
That setter is invoked on every change so you can easily debounce it ... something like (for the case above):

```haxe
function (v):Void {
  offset = v;
  debouncedUpdate();
}
```

where `debouncedUpdate` is defined as follows:

```haxe
var debouncedUpdate : Void -> Void;
// in constructor
debouncedUpdate = thx.Timer.debounce(update, 500); // trigger at most every half a sec
```

**Comment by fponticelli** [comment]
by the way, amazing work on the clipper port ... I tried several time to do something similar and I restart from scratches every other week ... my progresses (no clipping for now) are here: https://github.com/fponticelli/thx.geom

**Comment by azrafe7** [comment]
Now I get it. Thanks! 

Silly question: is there a way to access the `Options` so that I can clamp inside the setter using min/max?

I saw your geom lib before, but somehow forgot about it. Seems pretty interesting, and I see it has SVG path parsing too, which I could surely find an use for.

About the clipper port, I hope to add the Int64 feature someday (using hxBitcoin bigint?), but my recent attempts have all failed so far.
